# Copyright 2025 Pedro Henrique Panstein, Pedro Augusto Wilhelm, Mateus Henrique Bosquetti, Kaua Eggert, Vinícius Eduardo dos Santos.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-image-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-image-api
  template:
    metadata:
      labels:
        app: aws-image-api
    spec:
      containers:
      - name: aws-image-api
        image: hivqs79/portal-do-conselho_aws-image-api:latest
        ports:
        - containerPort: 3060
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-aws-image-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-aws-image-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-aws-image-config
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-aws-image-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-aws-image-secret
              key: password
        - name: REGION
          valueFrom:
            secretKeyRef:
              name: aws-image-secret
              key: region
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-image-secret
              key: access_key
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-image-secret
              key: secret_key
---
apiVersion: v1
kind: Service
metadata:
  name: aws-image-api-service
spec:
  selector:
    app: aws-image-api
  ports:
    - protocol: TCP
      port: 3060
      targetPort: 3060
  type: ClusterIP
