apiVersion: v1
kind: ConfigMap
metadata:
  name: front-env
data:
  NEXT_PUBLIC_URL_GENERAL_API: "http://general-api-service:8081"
  NEXT_PUBLIC_URL_CHAT_API: "http://chat-api-service:8082"
  NEXT_PUBLIC_URL_AWS_API: "http://aws-api-service:3060"
  NEXT_PUBLIC_URL_KAFKA_WORKSERVICE_API: "http://kafka-work-service:3090"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: front
        image: hivqs79/portal-do-conselho_front-app:latest
        envFrom:
          - configMapRef:
              name: front-env
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: front-app
