apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: general-api
  template:
    metadata:
      labels:
        app: general-api
    spec:
      containers:
      - name: general-api
        image: hivqs79/portal-do-conselho_general-api:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-general-config
              key: jdbc-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-general-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-general-secret
              key: password
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi                
        

---
apiVersion: v1
kind: Service
metadata:
  name: general-api-service
spec:
  selector:
    app: general-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
