apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topic
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: wurstmeister/kafka:latest
        command:
          - "sh"
          - "-c"
          - |
            kafka-topics.sh --create --topic notification --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
      restartPolicy: Never
  backoffLimit: 4
