apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi        
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9092
        env:
        # - name: KAFKA_ADVERTISED_LISTENERS
        #   value: "PLAINTEXT://kafka-service:9092"
        # - name: KAFKA_LISTENERS
        #   value: "PLAINTEXT://0.0.0.0:9092"
        # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: "PLAINTEXT:PLAINTEXT"
        # - name: KAFKA_INTER_BROKER_LISTENER_NAME
        #   value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://kafka-service:9092,OUTSIDE://localhost:9093"
        - name: KAFKA_LISTENERS
          value: "INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1Gi
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - name: outside
      port: 9093
      targetPort: 9093
    - name: inside
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-service
# spec:
#   type: ClusterIP
#   ports:
#     - name: kafka
#       port: 9092
#       targetPort: 9092
#   selector:
#     app: kafka
