# Copyright 2025 Pedro Henrique Panstein, Pedro Augusto Wilhelm, Mateus Henrique Bosquetti, Kaua Eggert, Vinícius Eduardo dos Santos.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-work-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-work-service
  template:
    metadata:
      labels:
        app: kafka-work-service
    spec:
      containers:
      - name: kafka-work-service
        image: hivqs79/portal-do-conselho_kafka-work-service:latest
        ports:
        - containerPort: 3090
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        resources:
          requests:
            cpu: 200m
            memory: 228Mi
          limits:
            cpu: 300m
            memory: 356Mi

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-work-service
spec:
  selector:
    app: kafka-work-service
  ports:
    - protocol: TCP
      port: 3090
      targetPort: 3090
  type: ClusterIP
