# Copyright 2025 Pedro Henrique Panstein, Pedro Augusto Wilhelm, Mateus Henrique Bosquetti, Kaua Eggert, Vinícius Eduardo dos Santos.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topic
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-creator
        image: wurstmeister/kafka:latest
        command:
          - "sh"
          - "-c"
          - |
            kafka-topics.sh --create --topic notification --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic chat_messages --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic room_events --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic annotationclass --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic annotationstudent --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic class --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic council --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic feedbackclass --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic feedbackstudent --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic feedbackuser --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic precouncilsection --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic precouncil --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic admin --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic customization --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic pedagogic --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic student --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic teacher --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            kafka-topics.sh --create --topic roomconversation --bootstrap-server kafka-service:9092 --partitions 1 --replication-factor 1
            
      restartPolicy: Never
  backoffLimit: 4
