apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-general-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-general-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-general-secret
type: Opaque
data:
  username: cm9vdA== 
  password: cm9vdA== 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-general-config
data:
  jdbc-url: jdbc:mysql://mysql-general-service:3306/general_db?createDatabaseIfNotExist=true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-general-deployment
spec:
  selector:
    matchLabels:
      app: mysql-general
  template:
    metadata:
      labels:
        app: mysql-general
    spec:
      containers:
      - name: mysql-general
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-general-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-general-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1Gi
      volumes:
      - name: mysql-general-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-general-pvc
      
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-general-service
spec:
  selector:
    app: mysql-general
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
