FROM node:16-alpine

WORKDIR /usr/src/app

COPY ../back/KafkaWorkService/package*.json ./

RUN npm install -g npm@8.19.2
RUN npm install

COPY ../back/KafkaWorkService .

EXPOSE 3090
CMD ["node", "index.js"]
